version: '3.7'
services:
  training_collector:
    restart: always
    container_name: training_collector
    build: application
    networks:
      - default
    ports:
      - "8000:8000"
      - "8080:8080"
    volumes:
      - type: bind
        source: /mnt/c/Users/kboga/PycharmProjects/trainingCollectorBeta/data
        target: /data

networks:
  default:
    driver: bridge
    name: custom_fl