# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protobufs import communications_pb2 as protobufs_dot_communications__pb2


class TrainingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetWeightsResults = channel.stream_stream(
                '/configuration.TrainingService/GetWeightsResults',
                request_serializer=protobufs_dot_communications__pb2.Weights.SerializeToString,
                response_deserializer=protobufs_dot_communications__pb2.Success.FromString,
                )


class TrainingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetWeightsResults(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrainingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetWeightsResults': grpc.stream_stream_rpc_method_handler(
                    servicer.GetWeightsResults,
                    request_deserializer=protobufs_dot_communications__pb2.Weights.FromString,
                    response_serializer=protobufs_dot_communications__pb2.Success.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'configuration.TrainingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TrainingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetWeightsResults(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/configuration.TrainingService/GetWeightsResults',
            protobufs_dot_communications__pb2.Weights.SerializeToString,
            protobufs_dot_communications__pb2.Success.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
